#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'About',    url: 'about'}

#-------------------------------
# Projects Section

projects:
- {name: 'Sunset'     ,     url: 'Sunset'}
- {name: 'OrangeCircles',   url: 'OrangeCircles'}
- {name: 'Connections',     url: 'Connections'}
- {name: 'Circling',        url: 'Circling'}
- {name: 'MarchingSquares', url: 'MarchingSquares'}

#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/timooo0'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Generative art portfolio by Timooo0 '
  rel-author: 'Timooo0'
  rel-publisher: ''

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
